# Generated by Django 6.0.2 on 2026-04-11 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chatmessage_commonpost_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-points', '-reputation_score']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their college email'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, help_text='Points earned from contributions (posts, helpful comments, etc.)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.FloatField(default=0.0, help_text='Overall reputation based on community interactions', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='student', help_text='User role determining permissions and capabilities', max_length=20),
        ),
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0, help_text='Total number of posts created', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_comments', models.IntegerField(default=0, help_text='Total number of comments made', validators=[django.core.validators.MinValueValidator(0)])),
                ('helpful_comments', models.IntegerField(default=0, help_text='Number of comments marked as helpful', validators=[django.core.validators.MinValueValidator(0)])),
                ('reports_submitted', models.IntegerField(default=0, help_text='Number of content reports submitted', validators=[django.core.validators.MinValueValidator(0)])),
                ('violations', models.IntegerField(default=0, help_text='Number of community guideline violations', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time user was active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='User this ranking belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Rankings',
                'ordering': ['-user__points', '-user__reputation_score'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment/Bullying'), ('misinformation', 'Misinformation'), ('plagiarism', 'Plagiarism'), ('off_topic', 'Off Topic'), ('other', 'Other')], help_text='Reason for reporting', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', help_text='Current status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the moderator/admin')),
                ('post', models.ForeignKey(help_text='The post being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.commonpost')),
                ('reporter', models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator/Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'reporter')},
            },
        ),
    ]
