# Generated by Django 6.0.2 on 2026-04-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_is_verified_user_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reputation_score',
        ),
        migrations.DeleteModel(
            name='UserRanking',
        ),
    ]
