# Generated by Django 6.0.2 on 2026-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_report_moderationaction_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
