# Generated by Django 6.0.2 on 2026-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_commentlike_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the comment is deleted'),
        ),
        migrations.AddField(
            model_name='commonpost',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the post is deleted'),
        ),
    ]
