# Generated by Django 6.0.2 on 2026-04-27 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_comment_deleted_commonpost_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted_globally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonpost',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
