# Generated by Django 6.0.2 on 2026-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_hash',
            field=models.CharField(max_length=64),
        ),
    ]
